spring:
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    show-sql: true
  datasource:
    url: jdbc:postgresql://ec2-44-213-151-75.compute-1.amazonaws.com:5432/d1es3jttn9i6dp
    username: piprnsdckrgotf
    password: 47193a634bd00b1855fa1ee5e35f325619a8758cc5f4a3c43736213a03d659f5
    driver-class-name: org.postgresql.Driver
  security:
    filter:
      enabled: true
      whitelist: >
        /api/v1/auth/**,
        /api/v1/public/**,
        /v3/api-docs/**,
        /swagger-ui/**,
        /v2/api-docs/**,
        /swagger-resources/**


jwt:
  secret: 3F4428472B4B6250655368566D5970337336763979244226452948404D635166
  expiration: 86400000 # 1 day
  refresh:
    expiration: 604800000 # 7 days

cloudinary:
  cloud-name: ddd
  api-key: 111
  api-secret: 222


