spring:
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    show-sql: true
  datasource:
    url: jdbc:postgresql://containers-us-west-96.railway.app:6584/railway
    username: postgres
    password: Zaac43FETvJ1K6D7dlxb
    driver-class-name: org.postgresql.Driver
  security:
    filter:
      enabled: true
      whitelist: >
        /api/v1/auth/**,
        /api/v1/public/**,
        /v3/api-docs/**,
        /swagger-ui/**,
        /v2/api-docs/**,
        /swagger-resources/**


  mail:
    username: destek.dibt@gmail.com
    password: knvwkxqhwmhqktlx
    port: 587
    host: smtp.gmail.com
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true



jwt:
  secret: 3F4428472B4B6250655368566D5970337336763979244226452948404D635166
  expiration: 86400000 # 1 day
  refresh:
    expiration: 604800000 # 7 days


cors:
  allowed-origins: >
    http://localhost:3000,
    http://localhost:8080,
    http://localhost:4200,
    https://test-dibt.up.railway.app,
    *
  allowed-methods: "*"
  allowed-headers: "*"
  exposed-headers: "Authorization,Link,X-Total-Count"
  allow-credentials: true
  max-age: 1800


cloudinary:
  api-key: 737629351212119
  api-secret: RKI6WkSG4ohV-kA5f6kyJH2-XIE
  cloud-name: dp1yugjn4

api:
  v1:
    posts:
      get-all: https://test-dibt.up.railway.app/api/v1/posts?page=%d&size=%d

cookie:
  refresh-token:
    max-age: 604800 # 7 days
  access-token:
    max-age: 86400 # 1 day

