spring:
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    show-sql: true
  datasource:
    url: jdbc:postgresql://localhost:5432/dibt-test
    username: postgres
    password: 12345
    driver-class-name: org.postgresql.Driver
  security:
    filter:
      enabled: true
      whitelist: >
        /api/v1/auth/**,
        /api/v1/public/**,
        /v3/api-docs/**,
        /swagger-ui/**,
        /v2/api-docs/**,
        /swagger-resources/**


  mail:
    username: destek.dibt@gmail.com
    password: knvwkxqhwmhqktlx
    port: 587
    host: smtp.gmail.com
    properties:
        mail:
            smtp:
              auth: true
              starttls:
                enable: true



jwt:
  secret: 3F4428472B4B6250655368566D5970337336763979244226452948404D635166
  expiration: 86400000 # 1 day
  refresh:
    expiration: 604800000 # 7 days


cors:
    allowed-origins: >
        http://localhost:3000,
        http://localhost:8080,
        http://localhost:4200,
    allowed-methods: "*"
    allowed-headers: "*"
    exposed-headers: "Authorization,Link,X-Total-Count"
    allow-credentials: true
    max-age: 1800


cloudinary:
  api-key: 123456789012345
  api-secret: 1234567890123456789012345678901234567890
  cloud-name: dibt-test


